sudo: false

language: go

go:
  - 1.6.3

go_import_path: github.com/cloudinsight/cloudinsight-agent

script:
  - make test
  - make test-cover-html

after_success:
  - bash <(curl -s https://codecov.io/bash)
